config/routes.rb
Rails.application.routes.draw do
  get 'pages/new'

  get 'pages/show'

  root 'static_pages#home'

  get 'static_pages/browse'

  get 'static_pages/search'

  get 'static_pages/create'

  get 'static_pages/about'

  get 'login' => 'static_pages#login'

  get 'login_new' => 'users#new'

  get 'login_existing' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  get 'stories/new'

  get 'stories/create'

  get 'display_story_links/byName'

  get 'display_story_links/byAuthor'

  get 'display_story_links/byLocation'

  get 'display_story_links/byTravelCategory'

  get 'display_story_links/byStoryType'

  get 'text_elements/new'

  get 'image_elements/new'

  get 'pages/prev'

  get 'pages/next'

  get 'stories/done'

  resources :users

  resources :stories

  resources :pages

  resources :text_elements

  resources :image_elements

  resources :search_links

end

app/views/pages/edit.html.erb
               <button class="serializeButton"> Save Layout </button>
                <script type="text/javascript">
                    var gridster;

                    $(function(){
                        gridster = $(".gridster ul").gridster({
                            widget_base_dimensions: [25, 25],
                            widget_margins: [1, 1],
                            extra_rows: 4,
                            helper: 'clone',
                            resize: {
                                enabled: true
                            }
                        }).data('gridster');
                    });

                </script>
                <script type="text/javascript">
                $('.serializeButton').on('click', function(){

                        var gridster2 = $(".gridster ul").gridster().data('gridster');
                        $(function(){
                            gridster2 = $(".gridster ul").gridster({
                                widget_margins: [1, 1],
                                widget_base_dimensions: [25, 25],
                                extra_rows:4,
                                serialize_params: function($w, wgd) { 
                                    return { 
                                        id: $($w).attr('id'), 
                                        col: wgd.col, 
                                        row: wgd.row, 
                                        size_x: wgd.size_x, 
                                        size_y: wgd.size_y,
                                        htmlContent: $($w).html()
                                    };
                                }
                            })
                            var gridster2 = $(".gridster ul").gridster().data('gridster');
                            gridData = gridster2.serialize();
                        });                            
                        $(function(){
                            $.ajax({
                                url: 'layoutHandler.php',
                                type: 'POST',
                                data: {json: gridData},
                                success: function(gridData){
                                    alert("Page Saved");
                                },
                                error: function(xhr, desc, err){
                                    alert (xhr.message);
                                }
                            })
                        });
                    });
                </script>
                <script>
                    $(document).ready(function(){
                        $("#imageBox1").resize(function(){
                            $("#image1").height($("#imageBox1").height());
                            $("#image1").width($("#imageBox1").width());
                        });
                    });
                </script>
                <script>
                    $(document).ready(function(){
                        $("#imageBox2").resize(function(){
                            $("#image2").height($("#imageBox2").height());
                            $("#image2").width($("#imageBox2").width());
                        });
                    });
                </script>
                <script>
                    $(document).ready(function(){
                        $("#imageBox3").resize(function(){
                            $("#image3").height($("#imageBox3").height());
                            $("#image3").width($("#imageBox3").width());
                        });
                    });
                </script>
                <script>
                    $(document).ready(function(){
                        $("#imageBox4").resize(function(){
                            $("#image4").height($("#imageBox4").height());
                            $("#image4").width($("#imageBox4").width());
                        });
                    });
                </script>
                <script>
                    $(document).ready(function(){
                        $("#imageBox5").resize(function(){
                            $("#image5").height($("#imageBox5").height());
                            $("#image5").width($("#imageBox5").width());
                        });
                    });
                </script>
                <script>
                    $(document).ready(function(){
                        $("#imageBox6").resize(function(){
                            $("#image6").height($("#imageBox6").height());
                            $("#image6").width($("#imageBox6").width());
                        });
                    });
                </script>
                <script>
                    $(document).ready(function(){
                        $("#imageBox7").resize(function(){
                            $("#image7").height($("#imageBox7").height());
                            $("#image7").width($("#imageBox7").width());
                        });
                    });
                </script>
                <script>
                    $(document).ready(function(){
                        $("#imageBox8").resize(function(){
                            $("#image8").height($("#imageBox8").height());
                            $("#image8").width($("#imageBox8").width());
                        });
                    });
                </script>
                <script>
                    $(document).ready(function(){
                        $("#imageBox9").resize(function(){
                            $("#image9").height($("#imageBox9").height());
                            $("#image9").width($("#imageBox9").width());
                        });
                    });
                </script>
                <script>
                    $(document).ready(function(){
                        $("#imageBox10").resize(function(){
                            $("#image10").height($("#imageBox10").height());
                            $("#image10").width($("#imageBox10").width());
                        });
                    });
                </script>

app/views/pages/new.html.erb
<span class='displayPageNum'>Page <%= session[:working_page] %> </span>
<div class='newPageEditor'>
  <div class='newStoryInsertSelector'>
    <%= button_to "Insert Text Box", text_elements_new_path, method: :get, class: 'insertButtons' %>
    <%= button_to "Insert Image", image_elements_new_path, method: :get, class: 'insertButtons' %>
    </br>
  </div>
  <div class='pageElementsViewer'>
    <span class=pageElementsLabel> Page Elements: </span>
    <div class="pageTextBoxViewer">
      <ul>
        <% text_elements = get_text_elements_for_page%>
        <% set_working_text_element(text_elements.length + 1) %>
        <% if text_elements.length > 0 %>
          <li>Text Elements:</li></br>
          <% text_elements.each do |text| %>
            <li>
              <div><%= link_to("Box #{text.num}", edit_text_element_path(text)) %></div> 
              <div><%= button_to("Remove", text, method: :delete) %></div>
            </li>
          <% end %>
        <% end %>
        <% image_elements = get_image_elements_for_page%>
        <% set_working_image_element(text_elements.length + 1) %>
        <% if image_elements.length > 0 %>
          <li>Image Elements:</li></br>
          <% image_elements.each do |image| %>
            <li>
              <div><%= link_to("Image #{image.num}", edit_image_element_path(image)) %></div> 
              <div><%= button_to("Remove", image, method: :delete) %></div>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<div class='storyButtons'>
  <ul>
    <li><%= button_to "Done", stories_done_path, method: :get %></li>
    <li><%= button_to "Set Layout for Page", { controller: 'pages', action: 'edit', id: working_page.id }, method: :get %></li>
    <li><%= button_to "Prev Page", pages_prev_path, method: :get %></li>
    <li><%= button_to "Next Page", pages_next_path, method: :get %></li>
  </ul>
</div>
</br>

app/views/pages/show.html.erb
<%= @text_elements.first.content %>
<%= image_tag @image_elements[1].path.url if @image_elements[1] %>
<%= @index %>

<%= button_to "Prev Page", @prev_page, method: :get if @prev_page %>
<%= button_to "Next Page", @next_page, method: :get if @next_page %>