config/routes.rb
Rails.application.routes.draw do
  get 'pages/new'

  get 'pages/show'

  root 'static_pages#home'

  get 'static_pages/browse'

  get 'static_pages/search'

  get 'static_pages/create'

  get 'static_pages/about'

  get 'login' => 'static_pages#login'

  get 'login_new' => 'users#new'

  get 'login_existing' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  get 'stories/new'

  get 'stories/create'

  get 'display_story_links/byName'

  get 'display_story_links/byAuthor'

  get 'display_story_links/byLocation'

  get 'display_story_links/byTravelCategory'

  get 'display_story_links/byStoryType'

  get 'text_elements/new'

  get 'image_elements/new'

  get 'pages/prev'

  get 'pages/next'

  get 'stories/done'

  resources :users

  resources :stories

  resources :pages

  resources :text_elements

  resources :image_elements

  resources :search_links

end

app/views/layouts/_header.html.erb
<header class="navbar">
  <div class="container">
    <nav>
      <ul>
        <li>
          <label for="logo">
            <%= link_to image_tag("logo_round.png", height: 45, width: 45), controller: 'static_pages', action: 'home' %>
          </label>
        </li>
        <% if logged_in? %>
          <% user = User.find(session[:user_id]) %>
          <li class='navItemUser'><%= link_to "Browse", controller: 'static_pages', action: 'browse' %></li>
          <li class='navItemUser'><%= link_to "Search", controller: 'static_pages', action: 'search' %></li>
          <li class='navItemUser'><%= link_to "Logout", logout_path, method: "delete" %></li>
          <% if working_story? %>
            <li class='navItemUser'><%= link_to "Edit Story", controller: 'static_pages', action: 'create' %></li>
          <% else %>
            <li class='navItemUser'><%= link_to "Create New Story!", controller: 'static_pages', action: 'create' %></li>
          <% end %>
          <li class='navItemUser'><%= link_to "My Stories", user %></li>
          <li class='navItemUser'><%= link_to "About", controller: 'static_pages', action: 'about' %></li>
        <% else %>
          <li class='navItemGuest'><%= link_to "Browse", controller: 'static_pages', action: 'browse' %></li>
          <li class='navItemGuest'><%= link_to "Search", controller: 'static_pages', action: 'search' %></li>
          <li class='navItemGuest'><%= link_to "Login", login_path %></li>
          <li class='navItemGuest'><%= link_to "About", controller: 'static_pages', action: 'about' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TravelStories</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>

    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>